import React from "react";
import { useParams, Link } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, Share2, FileDown } from "lucide-react";
import { useScanDetail } from "@/hooks/useScanDetail";
import ScanDetail from "@/components/dashboard/ScanDetail";
import { useToast } from "@/hooks/use-toast";
import html2pdf from "html2pdf.js";

export default function SharedScanView() {
  const { id } = useParams<{ id: string }>();
  const { scan, loading, error } = useScanDetail(id || null);
  const { toast } = useToast();

  const handleShare = () => {
    if (!scan) return;

    const link = window.location.href;
    navigator.clipboard.writeText(link).then(() => {
      toast({
        title: "Đã sao chép",
        description: "Link chia sẻ đã được sao chép vào clipboard",
      });
    }).catch(() => {
      toast({
        title: "Lỗi",
        description: "Không thể sao chép link",
        variant: "destructive",
      });
    });
  };

  const handleExportPDF = () => {
    if (!scan) return;

    const content = document.getElementById("shared-scan-report");
    if (!content) {
      toast({
        title: "Lỗi",
        description: "Không thể tìm thấy nội dung để xuất PDF",
        variant: "destructive",
      });
      return;
    }

    const options = {
      margin: 1,
      filename: `SEO-Report-${scan.url.replace(/[^a-z0-9]/gi, '_')}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    html2pdf().set(options).from(content).save();
    
    toast({
      title: "Đang xuất PDF",
      description: "File PDF sẽ được tải xuống trong giây lát",
    });
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center space-y-4">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto"></div>
          <p className="text-muted-foreground">Đang tải...</p>
        </div>
      </div>
    );
  }

  if (error || !scan) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Card className="w-full max-w-md mx-4">
          <CardHeader>
            <CardTitle className="text-center">❌ Không tìm thấy</CardTitle>
          </CardHeader>
          <CardContent className="text-center space-y-4">
            <p className="text-muted-foreground">
              {error ? "Có lỗi xảy ra khi tải dữ liệu" : "Bản phân tích không tồn tại hoặc đã bị xóa"}
            </p>
            <Link to="/">
              <Button variant="outline" className="gap-2">
                <ArrowLeft className="h-4 w-4" />
                Về trang chủ
              </Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="border-b bg-card">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link to="/">
                <Button variant="outline" size="sm" className="gap-2">
                  <ArrowLeft className="h-4 w-4" />
                  Trang chủ
                </Button>
              </Link>
              <div>
                <h1 className="text-xl font-bold">📊 SEO Analysis Report</h1>
                <p className="text-sm text-muted-foreground">Shared public view</p>
              </div>
            </div>
            
            <div className="flex gap-2">
              <Button onClick={handleShare} variant="outline" size="sm" className="gap-2">
                <Share2 className="h-4 w-4" />
                Chia sẻ
              </Button>
              <Button onClick={handleExportPDF} variant="secondary" size="sm" className="gap-2">
                <FileDown className="h-4 w-4" />
                Xuất PDF
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="container mx-auto px-4 py-8">
        <div id="shared-scan-report">
          <ScanDetail scan={scan} />
        </div>
      </div>

      {/* Footer */}
      <div className="border-t bg-card mt-8">
        <div className="container mx-auto px-4 py-6 text-center">
          <p className="text-sm text-muted-foreground">
            This report was generated by SEO Auto Tool • {new Date().getFullYear()}
          </p>
        </div>
      </div>
    </div>
  );
}